### ISSUE TITLE
Range widget doesn't have default value

### ISSUE THREAD

**Issue by rgamez** [cobweb-eu/fieldtrip-authoring-tool#11]
Currently all the range widgets default to 0, it would be useful could set a default/suggested value in the designer.

**Comment by rgamez** [comment]
We need default option for single choice selection as well and potentially for all the fields.

> The fields a) future trend, b) future status and c) restoration possibility could only take one value (multi-choice is not an option) and XX (or unable to assess) could be the default value if the user wants to leave the field blank

**Comment by panterz** [comment]
The AT has been converted to Survey Designer. Check here for issues:
https://github.com/edina/survey-designer/issues
