### ISSUE TITLE
Create a group box widget

### ISSUE THREAD

**Issue by rgamez** [cobweb-eu/fieldtrip-authoring-tool#18]
Group a set of questions is a very common use case, for example for the following table:

Layer | Cover       | Height (m)
--------|---------------|---------------
Tree (>2m) | |
Shrub (0.5 - 2m) | |
Tree (<0.5m) | |

you could create two range widgets but they should be group under the Tree label

![tree widget](https://cloud.githubusercontent.com/assets/49568/6245817/5f950c3e-b75a-11e4-808d-b90abed1e337.png)

**Comment by panterz** [comment]
Not a priority
