### ISSUE TITLE
App not reporting GPS satellite numbers or accuracy in metres

### ISSUE THREAD

**Issue by samadammeek** [cobweb-eu/fieldtrip-authoring-tool#21]

**Comment by panterz** [comment]
Is it in a different metric system or it's not included at all?

**Comment by samadammeek** [comment]
There is no field measuring number of satellites and pos_acc is always -1:

https://dyfi.cobwebproject.eu/geoserver/public/wfs?service=wfs&version=1.0.0&request=GetFeature&typeName=cobweb:sid-5ee5de94-5acf-46bd-a4af-fc4b2bc8239d&outputFormat=application/json&srsName=EPSG:4236

**Comment by panterz** [comment]
@samadammeek found the bug but need to discuss something before I commit the fix. We need to capture 2 events:
1. when the GPS times outs
2. when the user moves the marker manually.

I would recommend something like null for case 1 and -1 for case 2. What do you think?

**Comment by samadammeek** [comment]
@panterz 
1. null is good for this
2. -1 is fine. The process will probably just skip these records or flag the issue in the metadata.

**Comment by xmichael** [comment]
@samadammeek I am thinking that null or anything that is not float (e.g. a double if I recall correctly) might break either the WFS or WPS. 

Maybe we could use 0  instead of null for case 1?

**Comment by samadammeek** [comment]
@xmichael 

I've altered the 52N code to deal with NULL, float, double, the WPS will work fine. I can't talk for the WFS though....

**Comment by xmichael** [comment]
OK let's leave it at null then. I will change this to 0 on the serverside if the WFS breaks.

**Comment by panterz** [comment]
Functionality was applied. Here's the link for the app that does that:
http://cobwebsvc.edina.ac.uk/apps/COBWEB-debug.apk
Maybe some testing first @sebastianclarke ?

**Comment by MHiggins-EnvSys** [comment]
@panterz testing this just now - do you know if WiFi-provided location should produce a signature value?

Or is the source of the device location data irrelevant in the pos_acc value?

**Comment by panterz** [comment]
The pos_acc should give you:
1. null for when GPS times out
2. -1 for when the user moves the point
3. a float number that expresses the accuracy in meters. 

There's no info about signature value if the provided location is coming from Wi-fi. I don't know if there's such a thing. Is @samadammeek interested in something like this for quality assurance purposes?

**Comment by MHiggins-EnvSys** [comment]
Tested this using the debug apk you posted above Panos. All three conditions you listed were met successfully (I used a GPS fix for no. 3 until we know what result WiFi will produce). You can see the test result details [here](http://cobweb-ci.envsys.co.uk/admin/cobwebtesting/cobwebmanualtestresult/41/) if you wish.

**Comment by panterz** [comment]
I don't have permissions to access that page.

**Comment by MHiggins-EnvSys** [comment]
Sorry Panos, that was a mistake. The details are irrelevant anyway - it works as you described on the debug APK.

**Comment by panterz** [comment]
Cool, thanks for testing.

**Comment by MasonJohnDavis** [comment]
Just a quick question Panos - if the user moves the pin manually do we
store the original location within the observation?

**Comment by MHiggins-EnvSys** [comment]
App version 0.1.0 appears to be storing all location values as -1 regardless of location settings. I tried using the GPS location, changing the location manually and letting GPS time out on both of these surveys:
[Survey A](https://dyfi.cobwebproject.eu/geonetwork/public/eng/catalog.search#/metadata/5d6026a4-c25e-404a-b5b5-74dcdfc4b2fb)
[Survey B](https://dyfi.cobwebproject.eu/geonetwork/public/eng/catalog.search#/metadata/350f2599-eba3-4217-8d55-292ad2ff16a8)
Additionally, I tested this with Debug GPS On and then Off. It made no difference - all records returned pos_acc of -1.

**Comment by MHiggins-EnvSys** [comment]
During testing the latest APK v 0.1.1 for Ruben's changes I have investigated this problem again. It still persists, as can be seen in the results for [this survey](https://dyfi.cobwebproject.eu/geonetwork/public/eng/catalog.search#/metadata/8ca17635-b54a-472f-90b0-2113c379f4d9) (three records labelled appropriately, each indicating their location settings).
All pos_acc = -1.

**Comment by panterz** [comment]
The AT has been converted to Survey Designer. Check here for issues:
https://github.com/edina/survey-designer/issues
