### ISSUE TITLE
Removing field leaves floating 'Add' button

### ISSUE THREAD

**Issue by sebastianclarke** [cobweb-eu/fieldtrip-authoring-tool#22]
When you add a new field to the designer, it also puts an 'Add' button below it, for adding further fields afterwards.

When you click the 'X' to remove this field, the 'Add' button should be removed as well, but still remains, leaving duplicate 'Add' buttons

**Comment by gmh04** [comment]
moved issue to https://github.com/edina/fieldtrip-cobweb-project/issues/137
